### ISSUE TITLE
Change project structure

### ISSUE THREAD

**Issue by HyunggyuJang** [AstarNetwork/astar-wasm-contracts-examples#1]
With current project, i.e.  

```sh
tree uniswap-dex-example
```

    .
    ├── Cargo.toml
    ├── README.md
    ├── tests
    └── uniswap-v2
        ├── Cargo.toml
        ├── lib.rs
        ├── contracts
        ├── impls
        └── traits

LSP (e.g. rust-analyzer) do not anything when it comes to editing the files under `contracts` with  

```sh
cat uniswap-dex-example/Cargo.toml
```

    [workspace]
    members = [
        "uniswap-v2/contracts/*",
    ]
    
    exclude = [
        "uniswap-v2"
    ]

I suggest to take contracts directory out of the project folder, `uniswap-v2`.  
E.g.  

```sh
tree uniswap-dex-example
```

    .
    ├── Cargo.toml
    ├── README.md
    ├── contracts
    ├── tests
    └── uniswap-v2
        ├── Cargo.toml
        ├── lib.rs
        ├── impls
        └── traits

with  

```sh
cat uniswap-dex-example/Cargo.toml
```

    [workspace]
    members = [
        "contracts/*",
    ]

In this way, LSP does duly expected job.

**Comment by PierreOssun** [comment]
Hey @HyunggyuJang 
You can do a Pull Request now

**Comment by HyunggyuJang** [comment]
Got it, will work on that.
